---
title: "Visual feature extraction"
author: "Chanuwas (New) Aswamenakul"
output: html_notebook
---

# Importing libraries & parameter setting

```{r}
library(tidyverse)
library(data.table)
library(abind)
library(lubridate)
library(stringr)
library(imager)
library(Rtsne)
library(ggrepel)

home_dir <- path.expand("~")
picasso_path <- file.path(home_dir, "Library/CloudStorage/Box-Box/QuantifyingPicasso")

bob_ross_path <- file.path(picasso_path, "bob_ross")
br_data_path <- file.path(bob_ross_path, "bob_ross_data")

cezanne_path <- file.path(picasso_path, "cezanne")
c_data_path <- file.path(cezanne_path, "cezanne_data")

monet_path <- file.path(picasso_path, "monet")
m_data_path <- file.path(monet_path, "monet_data")

target_cat <- "painting"
feature_model <- "resnet"
```

# Data loading
## Picasso
```{r}
# artwork tabular data
art_data <- read.delim("raw_data/artwork1.csv", colClasses = "character") # /t as separator

# row whose columns are shifted
tmp_ind <- art_data[art_data$opp == "OPP.36:312",] %>% rownames()
art_data[tmp_ind, 2] <- paste(art_data[tmp_ind, 2], art_data[tmp_ind, 3])
for (i in 3:ncol(art_data)-1) {
  art_data[tmp_ind, i] <- art_data[tmp_ind, i+1]
}

# parse out date, month, and year variables from existing columns
art_data <- art_data %>% 
  separate(dateEnd, c("yearEnd","monthEnd","dayEnd"), remove = FALSE) %>% 
  separate(dateStart, c("yearStart","monthStart","dayStart"), remove = FALSE) %>% 
  mutate(yearEnd = as.numeric(yearEnd),
         monthEnd = as.numeric(monthEnd),
         dayEnd = as.numeric(dayEnd),
         yearStart = as.numeric(yearStart),
         monthStart = as.numeric(monthStart),
         dayStart = as.numeric(dayStart))

# remove weird data (7 entries)
art_data <- art_data %>%
  filter(category != "") %>% # empty rows
  filter(yearEnd != 0) # 2 entries w/ missing end dates

# number of years to finish
art_data <- art_data %>%
  mutate(yearDuration = yearEnd - yearStart)

# fill months and dates
art_data <- art_data %>% 
  mutate(monthEnd_fix = case_when(monthEnd == 0 ~ 6.5,
                                  TRUE ~ monthEnd),
         dayEnd_fix = case_when(dayEnd == 0 ~ 15.5,
                                  TRUE ~ dayEnd),
         monthStart_fix = case_when(monthStart == 0 ~ 6.5,
                                  TRUE ~ monthStart),
         dayStart_fix = case_when(dayStart == 0 ~ 15.5,
                                  TRUE ~ dayStart)) %>%
  mutate(dateEnd = make_date(yearEnd, monthEnd_fix, dayEnd_fix), # convert dateEnd into date type
         dateStart = make_date(yearStart, monthStart_fix, dayStart_fix), # convert dateStart into date type
         yearMonthStart = yearStart + monthStart_fix/12 + dayStart_fix/365) %>% # convert date into year scale
  mutate(date_duration = dateEnd - dateStart)

# select necessary columns
reduced_art <- art_data %>% 
  select(opp, title, category, monthStart, yearStart, yearMonthStart)

paintings <- reduced_art %>% 
  filter(category == target_cat)

# Set up non-overlapping windows
annualBins <- 12 # 12 months
windowSize <- 1/annualBins # window size on the year scale (1 month)

# major artistic periods
majorPeriodOnset <- tibble(period = c("Blue",
                                      "Rose",
                                      "Les Demoiselles d'Avignon",
                                      "Horta de Hebra landscapes",
                                      "Analytic Cubism",
                                      "Synthetic Cubism",
                                      "WW1 Start",
                                      "Neoclassicism", 
                                      "Surrealism\n(Mandoline et guitare)",
                                      "Surrealism\n(Trois denseurs)"),
                           yearMonthStart = c(1901,
                                              1904, 
                                              1907.583,
                                              1909.750,
                                              1912 + 9/12, # changed from 9/12
                                              1912.5,
                                              1914.5, 
                                              1918, 
                                              1924.583, 
                                              1925+2/12)) %>% 
  mutate(timeWindow = ceiling(yearMonthStart / windowSize) * windowSize,
         onsetYear = floor(timeWindow))

preduced_art <- reduced_art
```


## Bob Ross
```{r}
# artwork tabular data
art_data <- read.csv(file.path(br_data_path, "bob_ross_paintings.csv")) %>% 
  select(painting_index, painting_title, season, episode, num_colors)

# The Joy of Painting episode data with *date*
ep_data <- read.csv(file.path(br_data_path, "episode_data.csv"))
names(ep_data)[2] <- "episode"

# Merge release date data with painting index
reduced_art <- merge(x = art_data, y = ep_data, by = c("season", "episode")) %>% 
  select(painting_index, season, episode, title, release_date)

brreduced_art <- reduced_art
```

## Cezanne
```{r}
# artwork tabular data
art_data <- read.csv(file.path(c_data_path, "cezanne_paintings.csv"))

# Merge release date data with painting index
reduced_art <- art_data %>% 
  select(r_id, fwn_id, title, startYear, endYear)

# get the order of images sorted by filenames (order of PCA features)
img_dir <- file.path(cezanne_path, "paintings")

# enable local access to Box folder
c_img_paths <- list.files(file.path(img_dir))

trimmed_paths <- sub("\\.(.*)", "", c_img_paths)
pca_order <- data.frame(fwn_id=trimmed_paths)

creduced_art <- merge(reduced_art, pca_order, by="fwn_id")
```

## Monet
```{r}
# artwork tabular data
art_data <- read.csv(file.path(m_data_path, "monet_paintings.csv"))

# Merge release date data with painting index
reduced_art <- art_data %>% 
  select(cat_id, title, startYear, endYear)

# get the order of images sorted by filenames (order of PCA features)
img_dir <- file.path(monet_path, "paintings")

# enable local access to Box folder
m_img_paths <- list.files(file.path(img_dir))

trimmed_paths <- sub("\\.(.*)", "", m_img_paths)
pca_order <- data.frame(cat_id=trimmed_paths)

mreduced_art <- merge(reduced_art, pca_order, by="cat_id")
```


# Code testing
```{r}
# model loading
# vgg16 (https://neurohive.io/en/popular-networks/vgg16/)
# base_model <- application_vgg16(weights = 'imagenet')
# summary(base_model) # display layer names
# 
# # extract intermediate layers
# model.conv1 <- keras_model(inputs = base_model$input,
#                            outputs = get_layer(base_model, 'block1_conv1')$output)
# model.pool1 <- keras_model(inputs = base_model$input,
#                            outputs = get_layer(base_model, 'block1_pool')$output)
# model.fc2 <- keras_model(inputs = base_model$input,
#                          outputs = get_layer(base_model, 'fc2')$output)
# 
# 
# # sample images
# year_list <- paintings %>% 
#   filter(yearStart >= 1900, yearStart <= 1970) %>% 
#   pull(yearStart) %>% unique()
# 
# sample_paintings <- paintings %>% 
#   filter(yearStart >= 1900, yearStart <= 1970) %>% 
#   group_by(yearStart) %>% 
#   do(head(., 30))
# 
# sample_opps <- sample_paintings %>% 
#   filter(yearStart == 1901) %>% 
#   pull(opp)
# 
# # image path
# img_dir <- file.path(picasso_path, "data_from_OPP/OPP_images/")
# 
# # reconstruct filename from OPP
# reconstruct_fn <- function(opp_str) {
#   return(paste0("yopp", substr(opp_str, 5, 6), "-", substr(opp_str, 8, 10), ".jpg"))
# }
# 
# # sample_images <- list.files(file.path("sample_images"), full.names = FALSE)
# # sample_path <- paste0("sample_images/", sample_images[1])
# # 
# # # reconstruct OPP id from file names
# # reconstruct_opp <- function(opp) {
# #   return(paste0("OPP.", substr(opp, 5, 6), ":", substr(opp, 8, 10)))
# # }
# # 
# # sample_images %>% reconstruct_opp
# 
# # load single image
# img <- image_load(sample_path, target_size = c(224,224))
# 
# # as.raster to plot
# x <- image_to_array(img)
# 
# if(to_plot) {
#   x %>%
#     as.raster(max=255L) %>% 
#     plot()
# }
# 
# x <- array_reshape(x, c(1, dim(x)))
# x <- imagenet_preprocess_input(x)
```

# Image feature extraction (Samples)

```{r}
# model loading
# feature_model <- "resnet"
# 
# if (feature_model == "vgg") {
#   # vgg model
#   base_model <- application_vgg16(weights = 'imagenet')
#   # intermediate layers
#   model.conv1 <- keras_model(inputs = base_model$input,
#                              outputs = get_layer(base_model, 'block1_conv1')$output)
#   model.pool1 <- keras_model(inputs = base_model$input,
#                              outputs = get_layer(base_model, 'block1_pool')$output)
#   model.fc <- keras_model(inputs = base_model$input,
#                           outputs = get_layer(base_model, 'fc2')$output)
# } else if (feature_model == "resnet") {
#   # resnet model
#   base_model <- application_resnet50(weights = 'imagenet')
#   # (None, 112, 112, 64)
#   model.conv1 <- keras_model(inputs = base_model$input,
#                              outputs = get_layer(base_model, 'conv1_conv')$output)
#   # (None, 56, 56, 64)
#   model.pool1 <- keras_model(inputs = base_model$input,
#                              outputs = get_layer(base_model, 'pool1_pool')$output)
#   # (None, 2048)
#   model.fc <- keras_model(inputs = base_model$input,
#                           outputs = get_layer(base_model, 'avg_pool')$output)
# }
# 
# 
# batch_size <- 30
# 
# # retrieve file names
# year_list <- paintings %>% 
#   pull(yearStart) %>% unique()
# 
# sample_paintings <- paintings %>% 
#   filter(yearStart >= 1900, yearStart <= 1970) %>% 
#   group_by(yearStart) %>% 
#   do(head(., batch_size))
# 
# # reconstruct filename from OPP
# reconstruct_fn <- function(opp_str) {
#   return(paste0("yopp", substr(opp_str, 5, 6), "-", substr(opp_str, 8, 10), ".jpg"))
# }
# 
# img_dir <- file.path(picasso_path, "data_from_OPP/OPP_images/")
# 
# # enable local access to Box folders
# for (year in year_list) {
#   tmp_filelist <- list.files(file.path(img_dir, year, "ythumbs"))
# }
# 
# # extract feature of each year (later convert into batch)
# low_features <- c()
# high_features <- c()
# 
# for (year in year_list) {
#   # construct file paths
#   sample_opps <- sample_paintings %>% 
#     filter(yearStart == year) %>% 
#     pull(opp)
#   
#   opp_paths <- sample_opps %>% 
#     reconstruct_fn() %>% 
#     file.path(img_dir, year, "ythumbs", .)
#   
#   x <- map(opp_paths,
#            ~image_load(.x, target_size = c(224,224), grayscale = FALSE) %>% 
#              image_to_array() %>% 
#              divide_by(255)
#          ) # result in list
#   x <- array(unlist(x), dim = c(224, 224, 3, length(x))) %>% # convert into an array
#     aperm(c(4,1,2,3))
#   
#   feature.conv1 <- model.conv1 %>%
#     predict(x) %>%
#     rowMeans(dims = 2)
#   feature.pool1 <- model.pool1 %>% 
#     predict(x) %>% 
#     rowMeans(dims = 2)
#   feature.fc <- model.fc %>% 
#     predict(x)
#   
#   low_features <- rbind(low_features, cbind(feature.conv1, feature.pool1))
#   high_features <- rbind(high_features, feature.fc)
# }
# 
# # filter out null (zero-valued) columns
# nz_masks <- high_features %>% 
#   colSums != 0
# high_features <- high_features[,nz_masks]
# 
# # PCA analysis for low-leven and high-level features
# low_features <- prcomp(low_features, center = TRUE, scale. = TRUE)$x[,1:100]
# colnames(low_features) <- paste0("low_pc", 1:100)
# 
# high_features <- prcomp(high_features, center = TRUE, scale. = TRUE)$x[,1:100]
# colnames(high_features) <- paste0("high_pc", 1:100)
# 
# # combine low-level and high-level features
# full_features <- cbind(low_features, high_features)
# 
# full_df <- data.frame(opp = sample_paintings$opp, yearMonthStart = sample_paintings$yearMonthStart)
# full_df <- cbind(full_df, low_features[,1:2], high_features[,1:2])
# full_df$yearStart <- sample_paintings$yearStart
```

# PCA on pre-processed image features
```{r}
# change path according to where the feature data are stored
artist <- "monet"

if (artist == "picasso") {
  feature_path <- file.path(picasso_path, "data_from_OPP/image_features")

  low_features <- fread(file.path(feature_path, paste0("low_feature_", target_cat, "_",
                                                       feature_model, "_test1.csv"))) %>% 
    as.data.frame()
  high_features <- fread(file.path(feature_path, paste0("high_feature_", target_cat, "_",
                                                        feature_model, "_test1.csv"))) %>%
    as.data.frame()
} else if (artist == "bob_ross") {
  feature_path <- file.path(picasso_path, "bob_ross", "bob_ross_data")

  low_features <- fread(file.path(feature_path, paste0("low_feature_",
                                                       feature_model, "_test1.csv"))) %>% 
    as.data.frame()
  high_features <- fread(file.path(feature_path, paste0("high_feature_",
                                                        feature_model, "_test1.csv"))) %>%
    as.data.frame()
} else if (artist == "cezanne") {
  feature_path <- file.path(picasso_path, "cezanne", "cezanne_data")

  low_features <- fread(file.path(feature_path, paste0("low_feature_",
                                                       feature_model, "_test1.csv"))) %>% 
    as.data.frame()
  high_features <- fread(file.path(feature_path, paste0("high_feature_",
                                                        feature_model, "_test1.csv"))) %>%
    as.data.frame()
} else if (artist == "monet") {
  feature_path <- file.path(picasso_path, "monet", "monet_data")

  low_features <- fread(file.path(feature_path, paste0("low_feature_",
                                                       feature_model, "_test1.csv"))) %>% 
    as.data.frame()
  high_features <- fread(file.path(feature_path, paste0("high_feature_",
                                                        feature_model, "_test1.csv"))) %>%
    as.data.frame()
}


# filter out null (zero-valued) columns
nz_masks <- high_features %>% 
  colSums != 0
high_features <- high_features[,nz_masks]

# PCA analysis for low-leven and high-level features
low.pca.results <- prcomp(low_features, center = TRUE, scale. = TRUE)
low_features <- low.pca.results$x[,1:100]
colnames(low_features) <- paste0("low_pc", 1:100)

high.pca.results <- prcomp(high_features, center = TRUE, scale. = TRUE)
high_features <- high.pca.results$x[,1:100]
colnames(high_features) <- paste0("high_pc", 1:100)

# combine low-level and high-level features
full_features <- cbind(low_features, high_features)

if (artist == "picasso") {
  load(paste0("track_list_", target_cat, "_", feature_model, ".Rdata"))

  # get the target category indices
  cat_opps <- reduced_art %>% 
    filter(category == target_cat) %>% 
    pull(opp)
  cat_filter <- track_list$opp %in% cat_opps
  
  # extract other features from the original dataset
  full_df <- data.frame(opp = track_list$opp[cat_filter]) %>% 
    left_join(reduced_art, by = "opp")
  full_df <- cbind(full_df, full_features)
  
  # save PCA results
  full_df %>%
    data.table() %>%
    fwrite(file.path(feature_path, paste0("pca_", target_cat, "_", feature_model, ".csv")))
} else {
  full_df <- cbind(reduced_art, full_features)
  
  # save PCA results
  full_df %>%
    data.table() %>%
    fwrite(file.path(feature_path, paste0("pca_", feature_model, ".csv")))
}
```

```{r}
# pca explained standard deviations
ggplot() +
  geom_point(aes(x = 1:length(low.pca.results$sdev), y = low.pca.results$sdev)) +
  geom_vline(xintercept = 100, color = "blue") +
  xlab("pca dimension") +
  ylab("explained sdev") +
  labs(title = "low-level feature pca")

ggplot() +
  geom_point(aes(x = 1:length(high.pca.results$sdev), y = high.pca.results$sdev)) +
  geom_vline(xintercept = 100, color = "blue") +
  xlab("pca dimension") +
  ylab("explained sdev") +
  labs(title = "high-level feature pca")
```

```{r}
pca_sd_list <- list(low_sd = low.pca.results$sdev,
                    high_sd = high.pca.results$sdev)

save(pca_sd_list, file = paste0("pca_sd_list", target_cat, "_", feature_model, ".Rdata"))
```


# PCA on combined data

```{r}
# Picasso
feature_path <- file.path(picasso_path, "data_from_OPP/image_features")
plow_features <- fread(file.path(feature_path, paste0("low_feature_", target_cat, "_",
                                                      feature_model, "_test2.csv"))) %>% 
  as.data.frame()
phigh_features <- fread(file.path(feature_path, paste0("high_feature_", target_cat, "_",
                                                       feature_model, "_test2.csv"))) %>%
  as.data.frame()

# Bob Ross
feature_path <- file.path(picasso_path, "bob_ross", "bob_ross_data")
brlow_features <- fread(file.path(feature_path, paste0("low_feature_",
                                                       feature_model, "_test2.csv"))) %>% 
  as.data.frame()
brhigh_features <- fread(file.path(feature_path, paste0("high_feature_",
                                                        feature_model, "_test2.csv"))) %>%
  as.data.frame()

# Cezanne
feature_path <- file.path(picasso_path, "cezanne", "cezanne_data")
clow_features <- fread(file.path(feature_path, paste0("low_feature_",
                                                      feature_model, "_test2.csv"))) %>% 
  as.data.frame()
chigh_features <- fread(file.path(feature_path, paste0("high_feature_",
                                                       feature_model, "_test2.csv"))) %>%
  as.data.frame()

# Monet
feature_path <- file.path(picasso_path, "monet", "monet_data")
mlow_features <- fread(file.path(feature_path, paste0("low_feature_",
                                                      feature_model, "_test2.csv"))) %>% 
  as.data.frame()
mhigh_features <- fread(file.path(feature_path, paste0("high_feature_",
                                                       feature_model, "_test2.csv"))) %>%
  as.data.frame()

# concatenating data frames
picasso_n <- nrow(plow_features)
bobr_n <- nrow(brlow_features)
c_n <- nrow(clow_features)
m_n <- nrow(mlow_features)

low_features <- rbind(plow_features, brlow_features, clow_features, mlow_features)
high_features <- rbind(phigh_features, brhigh_features, chigh_features, mhigh_features)

# filter out null (zero-valued) columns
nz_masks <- high_features %>% 
  colSums != 0
high_features <- high_features[,nz_masks]

# PCA analysis for low-leven and high-level features
low.pca.results <- prcomp(low_features, center = TRUE, scale. = TRUE)
low_features <- low.pca.results$x[,1:100]
colnames(low_features) <- paste0("low_pc", 1:100)

high.pca.results <- prcomp(high_features, center = TRUE, scale. = TRUE)
high_features <- high.pca.results$x[,1:100]
colnames(high_features) <- paste0("high_pc", 1:100)

summary(low.pca.results)$importance[2,1:100] %>% sum()
summary(high.pca.results)$importance[2,1:100] %>% sum()

# combine low-level and high-level features
full_features <- cbind(low_features, high_features)


# Picasso
p_start_ind <- 1
p_end_ind <- picasso_n
feature_path <- file.path(picasso_path, "data_from_OPP/image_features")
full_df <- cbind(paintings, full_features[p_start_ind:p_end_ind,])

# save PCA results
full_df %>%
  data.table() %>%
  fwrite(file.path(feature_path, paste0("pca_combined150_", target_cat, "_", feature_model, "_test2.csv")))


# Bob Ross
br_start_ind <- picasso_n + 1
br_end_inds <- picasso_n + bobr_n
feature_path <- file.path(picasso_path, "bob_ross", "bob_ross_data")
full_df <- cbind(brreduced_art, full_features[br_start_ind:br_end_inds,])

# save PCA results
full_df %>%
  data.table() %>%
  fwrite(file.path(feature_path, paste0("pca_combined150_", feature_model, "_test2.csv")))


# Cezanne
c_start_ind <- picasso_n + bobr_n + 1
c_end_inds <- picasso_n + bobr_n + c_n
feature_path <- file.path(picasso_path, "cezanne", "cezanne_data")
full_df <- cbind(creduced_art, full_features[c_start_ind:c_end_inds,])

# save PCA results
full_df %>%
  data.table() %>%
  fwrite(file.path(feature_path, paste0("pca_combined150_", feature_model, "_test2.csv")))


# Monet
m_start_ind <- picasso_n + bobr_n + c_n + 1
m_end_inds <- picasso_n + bobr_n + c_n + m_n
feature_path <- file.path(picasso_path, "monet", "monet_data")
full_df <- cbind(mreduced_art, full_features[m_start_ind:m_end_inds,])

# save PCA results
full_df %>%
  data.table() %>%
  fwrite(file.path(feature_path, paste0("pca_combined150_", feature_model, "_test2.csv")))
```

# PCA Picasso vs Bob Ross

```{r}
# Picasso
feature_path <- file.path(picasso_path, "data_from_OPP/image_features")
plow_features <- fread(file.path(feature_path, paste0("low_feature_", target_cat, "_",
                                                      feature_model, ".csv"))) %>% 
  as.data.frame()
phigh_features <- fread(file.path(feature_path, paste0("high_feature_", target_cat, "_",
                                                       feature_model, ".csv"))) %>%
  as.data.frame()

# Bob Ross
feature_path <- file.path(picasso_path, "bob_ross", "bob_ross_data")
brlow_features <- fread(file.path(feature_path, paste0("low_feature_",
                                                       feature_model, ".csv"))) %>% 
  as.data.frame()
brhigh_features <- fread(file.path(feature_path, paste0("high_feature_",
                                                        feature_model, ".csv"))) %>%
  as.data.frame()


# concatenating data frames
picasso_n <- nrow(plow_features)
bobr_n <- nrow(brlow_features)

low_features <- rbind(plow_features, brlow_features)
high_features <- rbind(phigh_features, brhigh_features)

# filter out null (zero-valued) columns
nz_masks <- high_features %>% 
  colSums != 0
high_features <- high_features[,nz_masks]

# PCA analysis for low-leven and high-level features
low.pca.results <- prcomp(low_features, center = TRUE, scale. = TRUE)
low_features <- low.pca.results$x[,1:100]
colnames(low_features) <- paste0("low_pc", 1:100)

high.pca.results <- prcomp(high_features, center = TRUE, scale. = TRUE)
high_features <- high.pca.results$x[,1:100]
colnames(high_features) <- paste0("high_pc", 1:100)

# combine low-level and high-level features
full_features <- cbind(low_features, high_features)



# Picasso
p_start_ind <- 1
p_end_ind <- picasso_n
feature_path <- file.path(picasso_path, "data_from_OPP/image_features")
full_df <- cbind(paintings, full_features[p_start_ind:p_end_ind,])

# save PCA results
full_df %>%
  data.table() %>%
  fwrite(file.path(feature_path, paste0("pca_p-vs-br_", target_cat, "_", feature_model, ".csv")))


# Bob Ross
br_start_ind <- picasso_n + 1
br_end_inds <- picasso_n + bobr_n
feature_path <- file.path(picasso_path, "bob_ross", "bob_ross_data")
full_df <- cbind(brreduced_art, full_features[br_start_ind:br_end_inds,])

# save PCA results
full_df %>%
  data.table() %>%
  fwrite(file.path(feature_path, paste0("pca_p-vs-br_", feature_model, ".csv")))

```

