---
title: "Style dimensionality"
author: "Chanuwas (New) Aswamenakul"
date: '2023-09-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(lubridate)
library(stringr)
library(rsample)
library(ggrepel)
library(patchwork)

home_dir <- path.expand("~")
picasso_path <- file.path(home_dir, "Library/CloudStorage/Box-Box/QuantifyingPicasso")

cbPalette <- c('#999999', '#E69F00', '#56B4E9', '#009E73', '#F0E442', '#0072B2', '#D55E00', '#CC79A7')
```

# Data loading

```{r, warning=FALSE}
art_data <- read.delim("raw_data/artwork1.csv", colClasses = "character") # /t as separator

# parse out date, month, and year variables from existing columns
art_data <- art_data %>% 
  separate(dateEnd, c("yearEnd","monthEnd","dayEnd"), remove = FALSE) %>% 
  separate(dateStart, c("yearStart","monthStart","dayStart"), remove = FALSE) %>% 
  mutate(yearEnd = as.numeric(yearEnd),
         monthEnd = as.numeric(monthEnd),
         dayEnd = as.numeric(dayEnd),
         yearStart = as.numeric(yearStart),
         monthStart = as.numeric(monthStart),
         dayStart = as.numeric(dayStart))

# remove weird data (8 entries)
art_data <- art_data %>%
  filter(category != "25~26-March/1936") %>% # shifted column (fixable)
  filter(category != "") %>% # empty rows
  filter(yearEnd != 0) # 2 entries w/ missing end dates

# number of years to finish
art_data <- art_data %>%
  mutate(yearDuration = yearEnd - yearStart)

# fill months and dates
art_data <- art_data %>% 
  mutate(monthEnd_fix = case_when(monthEnd == 0 ~ 6.5,
                                  TRUE ~ monthEnd),
         dayEnd_fix = case_when(dayEnd == 0 ~ 15.5,
                                  TRUE ~ dayEnd),
         monthStart_fix = case_when(monthStart == 0 ~ 6.5,
                                  TRUE ~ monthStart),
         dayStart_fix = case_when(dayStart == 0 ~ 15.5,
                                  TRUE ~ dayStart)) %>%
  mutate(dateEnd = make_date(yearEnd, monthEnd_fix, dayEnd_fix), # convert dateEnd into date type
         dateStart = make_date(yearStart, monthStart_fix, dayStart_fix), # convert dateStart into date type
         yearMonthStart = yearStart + monthStart_fix/12 + dayStart_fix/365) %>% # convert date into year scale
  mutate(date_duration = dateEnd - dateStart)

# select necessary columns
reduced_art <- art_data %>% 
  select(opp, title, category, dayStart, monthStart, yearStart, yearMonthStart, dateStart)

paintings <- reduced_art %>% 
  filter(category == "painting")

# Set up non-overlapping windows
annualBins <- 12 # 12 months
windowSize <- 1/annualBins # window size on the year scale (1 month)

# major artistic periods
majorPeriodOnset <- tibble(period = c("Blue",
                                      "Rose",
                                      "Les Demoiselles d'Avignon",
                                      "Horta de Hebra landscapes",
                                      "Analytic Cubism",
                                      "Synthetic Cubism",
                                      "WW1 Start",
                                      "Neoclassicism", 
                                      "Surrealism\n(Mandoline et guitare)",
                                      "Surrealism\n(Trois denseurs)"),
                           yearMonthStart = c(1901,
                                              1904, 
                                              1907.583,
                                              1909.750,
                                              1912 + 9/12, # changed from 9/12
                                              1912.5,
                                              1914.5, 
                                              1918, 
                                              1924.583, 
                                              1925+2/12)) %>% 
  mutate(timeWindow = ceiling(yearMonthStart / windowSize) * windowSize,
         onsetYear = floor(timeWindow))
```


# Load PCA results

```{r}
feature_path <- file.path(picasso_path, "data_from_OPP/image_features")
target_cat <- "painting"
feature_model <- "resnet"

full_df <- fread(file.path(feature_path, paste0("pca_", target_cat, "_", feature_model, ".csv"))) %>% 
  as.data.frame()

# Separate low-level and high-level features for analyses
low_cols <- str_detect(colnames(full_df), "low")
low_features <- full_df[low_cols]

high_cols <- str_detect(colnames(full_df), "high")
high_features <- full_df[high_cols]

full_pc_cols <- str_detect(colnames(full_df), "pc")
full_features <- full_df[full_pc_cols]
```


# Style dimensionality over time

```{r setup, include=FALSE}
ordered_df <- full_df %>% 
  left_join(art_data %>% select(opp, dayStart, dateStart),
            by = "opp") %>% 
  filter(monthStart != 0, dayStart != 0) %>% 
  arrange(yearStart, monthStart, dayStart) %>% 
  select(dateStart, low_pc1:high_pc100)

style_dim.df <- tibble()

first_date <- ymd(18950101)
last_date <- ymd(19720701)

year_window <- 5

window_size <- years(year_window)
wstep_size <- months(1)

wfirst_date <- first_date
wlast_date <- first_date + window_size

start_date_seq <- seq(first_date, last_date - window_size + months(1), by = "1 month")

while (wlast_date <= last_date) {
  print(paste("start date =", wfirst_date))
  
  full_df.subi <- ordered_df %>% 
    filter(dateStart >= wfirst_date, dateStart < wlast_date) %>% 
    select(-dateStart)
  
  print(paste("number of rows =", nrow(full_df.subi)))
  if (nrow(full_df.subi) > 0) {
    full_df.subi.pca <- prcomp(full_df.subi %>% slice_sample(n=50))
    cum.sdev.prop <- cumsum(full_df.subi.pca$sdev/sum(full_df.subi.pca$sdev))
    
    style_dim90 <- sum((cum.sdev.prop < .90)) + 1
    style_dim75 <- sum((cum.sdev.prop < .75)) + 1
    style_dim50 <- sum((cum.sdev.prop < .50)) + 1
    style_dim.df <- bind_rows(style_dim.df, 
                              tibble(dateStart = wfirst_date,
                                     n = nrow(full_df.subi),
                                     dim50 = style_dim50,
                                     dim75 = style_dim75,
                                     dim90 = style_dim90))
  } else {
    style_dim.df <- bind_rows(style_dim.df, 
                            tibble(dateStart = wfirst_date,
                                   n = 0,
                                   dim50 = 0,
                                   dim75 = 0,
                                   dim90 = 0))
  }
  
  wfirst_date <- wfirst_date + wstep_size
  wlast_date <- wlast_date + wstep_size
}

write_csv(style_dim.df,
          file.path(picasso_path, "results",
                    paste0("slide_window", year_window, "y_artdim1m.csv")))

# style_dim.df %>% filter(n < 20)

# window_size <- 1
# step_size <- 1
# 
# for(yeari in seq(1895,max(full_df$yearStart), step_size)){
#   full_df.subi <- full_df %>% 
#     filter(yearStart > yeari - window_size,
#            yearStart <= yeari) %>%
#     select(low_pc1:high_pc100)
#   
#   full_df.subi.pca <- prcomp(full_df.subi %>% slice_sample(n=50))
#   cum.sdev.prop <- cumsum(full_df.subi.pca$sdev/sum(full_df.subi.pca$sdev))
#   
#   style_dim90 <- sum((cum.sdev.prop < .90)) + 1
#   style_dim75 <- sum((cum.sdev.prop < .75)) + 1
#   style_dim50 <- sum((cum.sdev.prop < .50)) + 1
#   style_dim.df <- bind_rows(style_dim.df, 
#                             tibble(year = yeari,
#                                    n = nrow(full_df.subi),
#                                    dim50 = style_dim50,
#                                    dim75 = style_dim75,
#                                    dim90 = style_dim90))
#   
# }
```

```{r}
# boostrapping average number of dimensions across lifetime
dim_vector_baseline <- c()
for(i in 1:1000) {
  full_df.pca <- prcomp(full_df %>% select(low_pc1:high_pc100) %>% slice_sample(n=50))
  cum.sdev.prop <- cumsum(full_df.pca$sdev/sum(full_df.pca$sdev))
  style_dim90 <- sum((cum.sdev.prop < .90)) + 1
  dim_vector_baseline <- c(dim_vector_baseline, style_dim90)
}

hist(dim_vector_baseline)
```


```{r}

year_window <- 3
style_dim.df <- read_csv(file.path(picasso_path, "results",
                                   paste0("slide_window", year_window, "y_artdim1m.csv")))


style_dim.df %>% 
  select(-n) %>% 
  pivot_longer(!dateStart, names_to = "exp_sdev", values_to = "pca_count") %>% 
  ggplot(aes(x=dateStart, y=pca_count, color=exp_sdev)) +
  geom_line() +
  theme_classic()

ggsave("img/explained_pca_sdev.png")

style_dim.df %>% 
  ggplot(aes(x=dateStart, y=dim90)) +
  geom_line() +
  ylim(0,35) +
  theme_classic() +
  geom_smooth(method="lm") +
  geom_vline(data=majorPeriodOnset, aes(xintercept=yearMonthStart))

ggsave(paste0("img/pca", year_window, "y_dim90_majorperiod.png"),
       width = 12, height = 7)



ma <- function(x, n = 5){stats::filter(x, rep(1 / n, n), sides = 1)}
style_dim.df$dim90.ma <- style_dim.df$dim90 %>% ma(n = 10)

style_dim.df %>% 
  ggplot(aes(x=dateStart, y=dim90.ma)) +
  geom_line() +
  scale_y_continuous("Number of dimensions") +
  xlab("Date") +
  theme_classic() +
  geom_smooth(method="lm") +
  theme(text = element_text(size = 16),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))

ggsave("img/pca1y_dim90ma_majorperiod.png", width = 12, height = 7)
```


```{r}
slidw_df <- read_csv(file.path(picasso_path, "results",
                               "slide_window1y_burst1m.csv"))

step_dim_df <- slidw_df %>% 
  select(start_date, cstep_avg) %>% 
  filter(start_date >= "1895-01-01") %>% 
  left_join(style_dim.df %>% select(dateStart, dim75, dim90),
            by = join_by(start_date == dateStart))

cor.test(step_dim_df$cstep_avg, step_dim_df$dim90)

step_dim_df %>% 
  ggplot(aes(x=cstep_avg, y=dim90)) +
  geom_point() +
  theme_classic()

ggsave("img/cstep_dim90_scatter.png", width = 12, height = 7)
```


```{r}
# analyzing slope of PCA growth for different window sizes
window_size_list <- 2:10
step_size <- 1
style_dim.df <- tibble()

for(window_size in window_size_list) {
  print(window_size)
  sample_size <- 100000
  for(yeari in seq(1896,max(full_df$yearStart), step_size)){
    full_df.subi <- full_df %>% 
      filter(yearStart > yeari - window_size,
             yearStart <= yeari) 
    sample_sizei <- min(sample_size, nrow(full_df.subi))
  }
  
  for(yeari in seq(1896,max(full_df$yearStart), step_size)){
    full_df.subi <- full_df %>% 
      filter(yearStart > yeari - window_size,
             yearStart <= yeari) %>%
      select(low_pc1:high_pc100)
    
    full_df.subi.pca <- prcomp(full_df.subi %>% slice_sample(n=sample_sizei))
    cum.sdev.prop <- cumsum(full_df.subi.pca$sdev/sum(full_df.subi.pca$sdev))
    
    style_dim90 <- sum((cum.sdev.prop < .90)) + 1
    style_dim75 <- sum((cum.sdev.prop < .75)) + 1
    style_dim50 <- sum((cum.sdev.prop < .50)) + 1
    
    style_dim.df <- bind_rows(style_dim.df, 
                              tibble(window_size = window_size, 
                                     year = yeari,
                                     n = nrow(full_df.subi),
                                     sample_size = sample_sizei,
                                     dim50 = style_dim50,
                                     dim75 = style_dim75,
                                     dim90 = style_dim90))
    
  }
}


style_dim.df.slopes <- style_dim.df %>% 
  group_by(window_size) %>%
  summarize(slope = summary(lm(dim90 ~ year))$coefficients["year","Estimate"])

style_dim.df.slopes %>% 
  ggplot(aes(x=window_size, y=slope)) +
  geom_line() +
  geom_point() +
  theme_classic()

ggsave("img/wsize_slope_dim.png", width = 12, height = 7)
```

